# Generated by Django 5.1.2 on 2024-10-11 21:05

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_kyc_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='file_upload',
            field=models.FileField(blank=True, help_text='Upload a JPG, PNG, or PDF file. Max size: 10MB.', null=True, upload_to='uploads/', validators=[myapp.models.validate_file_type, myapp.models.validate_file_size]),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
